### ISSUE TITLE
replace 1st person model with Real Camera

### ISSUE THREAD

**Issue by RainyNyte** [ScytedTV-Studios/JuJus-Better-Wynncraft#1]
more a suggestion than an issue, but if you used Real Camera in the pack you would be able to remove 1st person model (which in my experience has usually ended up being a bigger resource drain than physics has) and shoulder surfing(covered by Real Camera's classic mode so remove or leave in at your discretion, not everyone who want's shoulder surfing style play is gonna want to have to turn it on in mod settings to get it), and possibly even not enough animations (though that one is up to preference since I don't know if real camera does anything to fill in gaps in the third person animations)

**Comment by JuJubeanYT** [comment]
Sorry I kinda stopped playin Wynncraft for a while so I didnt think about checking on my pack xD. Ill look into it and let u know in a day or 2 bc im busy with irl stuff -_-. Might be a while before me and Loyd update tho bc we dont rly play Wynncraft anymore (he vanished like my father or somethin idfk).

**Comment by JuJubeanYT** [comment]
Nvm bro is fast af. Updating now

**Comment by LoydOsborne** [comment]
Yup, it should be released everywhere within the next 1-2 hours!

**Comment by LoydOsborne** [comment]
These updates are being pushed to [Modrinth](https://modrinth.com/collection/9IenzBF9/modpacks), [Curseforge](https://www.curseforge.com/members/scytedtv/projects), and [ScytedTV Resources](https://www.scyted.tv/resources/jujus-better-wynncraft/). Curseforge may take a little time to verify the changes, but it should be available everywhere else.
